---
- include_role:
    name: geerlingguy.postgresql
    tasks_from: users
  vars:
    postgresql_users:
      - name: "{{ odoo_user }}"
        role_attr_flags: CREATEDB

- include_role:
    name: geerlingguy.postgresql
    tasks_from: databases
  vars:
    postgresql_databases:
      - name: "{{ database_name }}"
        owner: "{{ odoo_user }}"
