---
# Use python3 interpreter
ansible_python_interpreter: "/usr/bin/python3"

# Odoo vars
odoo_user: odoo
odoo_db_name: odoo

odoo_edition: oca
odoo_role_odoo_head: "8ef3986d58a097a04502d9ca1ee0a860d7230723"
odoo_core_modules: "crm,project,stock,sale_management,stock_account,base_address_city,crm_project,hr_timesheet,mail,hr_holidays,account,account_invoicing,account_asset,purchase,hr,hr_expense,account_analytic_default,account_bank_statement_import,account_cancel,analytic,auth_crypt,auth_signup,barcodes,base,base_automation,base_iban,base_import,base_setup,base_vat,base_vat_autocomplete,board,bus,calendar_sms,contacts,decimal_precision,document,fetchmail,google_account,google_calendar,google_drive,google_spreadsheet,hr_contract,iap,l10n_es,payment,payment_transfer,procurement_jit,product,product_margin,project_timesheet_holidays,resource,sale,sale_crm,sale_expense,sale_margin,sale_stock,sale_timesheet,sales_team,sms,utm,web,web_diagram,web_editor,web_kanban_gauge,web_planner,web_settings_dashboard,web_tour,calendar,portal,http_routin,crm_phone_validation,phone_validation"
odoo_community_modules: "account_banking_mandate,account_banking_pain_base,account_banking_sepa_credit_transfer,account_banking_sepa_direct_debit,account_due_list,account_financial_report,account_multicompany_easy_creation,account_payment_mode,account_payment_order,account_payment_partner,account_tax_balance,auth_brute_force,base_bank_from_iban,base_location,base_location_geonames_import,base_technical_features,contract,contract_sale_invoicing,contract_variable_qty_timesheet,contract_variable_quantity,date_range,l10n_es_account_asset,l10n_es_account_bank_statement_import_n43,l10n_es_account_invoice_sequence,l10n_es_aeat,l10n_es_aeat_mod111,l10n_es_aeat_mod115,l10n_es_aeat_mod303,l10n_es_aeat_mod349,l10n_es_mis_report,l10n_es_partner,l10n_es_toponyms,mail_tracking,mail_tracking_mailgun,mass_editing,mis_builder,module_auto_update,password_security,project_task_default_stage,report_xlsx,sale_order_invoicing_finished_task,sale_order_line_input,web_decimal_numpad_dot,web_favicon,web_no_bubble,web_responsive,web_searchbar_full_width,web_widget_color"

# Nginx configuration
nginx_configs:
  upstream:
    - upstream odoo { server 127.0.0.1:8069; }

nginx_sites:
  odoo:
    - |
      listen 80;
      server_name {{ inventory_hostname }};
      rewrite ^(.*)$ https://$host$1 permanent;
  odoo.ssl:
    - |
      listen 443 ssl;
      ssl_certificate /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      server_name {{ inventory_hostname }};
      proxy_read_timeout 720s;
      proxy_connect_timeout 720s;
      proxy_send_timeout 720s;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      ssl on;
      access_log /var/log/nginx/odoo.access.log;
      error_log /var/log/nginx/odoo.error.log;
      location / {
        proxy_redirect off;
        proxy_pass http://odoo;
      }
      gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
      gzip on;
